/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Salsabila Putri Ray
 */
public class TugasRumah_salsa extends javax.swing.JFrame {

    /**
     * Creates new form TugasRumah_salsa
     */
    public TugasRumah_salsa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        nomer = new javax.swing.JTextField();
        mapel = new javax.swing.JTextField();
        Nilai = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        oke = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Square721 BT", 0, 36)); // NOI18N
        jLabel1.setText("PENILAIAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(221, 14, 193, 45);

        jLabel2.setText("NAMA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(78, 85, 45, 20);

        jLabel3.setText("NO Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(78, 146, 72, 20);

        jLabel4.setText("MAPEL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(78, 216, 49, 20);

        jLabel5.setText("NILAI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(78, 290, 42, 20);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(264, 77, 250, 37);
        getContentPane().add(nomer);
        nomer.setBounds(264, 138, 250, 37);
        getContentPane().add(mapel);
        mapel.setBounds(264, 205, 250, 43);
        getContentPane().add(Nilai);
        Nilai.setBounds(264, 280, 250, 41);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane2.setViewportView(hasil);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(139, 368, 309, 195);

        oke.setText("OK");
        oke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okeActionPerformed(evt);
            }
        });
        getContentPane().add(oke);
        oke.setBounds(140, 330, 53, 29);

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(350, 330, 79, 29);

        setBounds(0, 0, 708, 687);
    }// </editor-fold>//GEN-END:initComponents

    private void okeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okeActionPerformed
        // TODO add your handling code here:
        String name = nama.getText();
        int absen = Integer.parseInt(nomer.getText());
        String pelajaran = mapel.getText();
        int nilai = Integer.parseInt(Nilai.getText());
        String predikat;
        if (nilai >=86 && nilai <=100){
            predikat = "Sempurna";
        }
        else if (nilai >=76 && nilai <=85){
            predikat = "Lulus";
        }
        else {
            predikat = "Tidak lulus";
        }
        
        hasil.append("Nama siswa : "+name+"\n"+"Nomor Absen : "+absen+"\n"+"Mata Pelajaran : "+pelajaran+"\n"+"Nillai : "+nilai+"\n"+"Predikat : "+predikat+"\n");
        
    }//GEN-LAST:event_okeActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        nomer.setText("");
        mapel.setText("");
        Nilai.setText("");
        hasil.setText("");
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasRumah_salsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasRumah_salsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasRumah_salsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasRumah_salsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasRumah_salsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nilai;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField mapel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nomer;
    private javax.swing.JButton oke;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
